### ISSUE TITLE
Initial Development Tracking

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie-release#1]
**Automate The Manual Release Steps From js-cookie**
- [x] <strike>Build routine to bump a JSON file version (https://github.com/js-cookie/js-cookie-release/issues/2)</strike>
- [x] <strike>Build routine to bump source file version (https://github.com/js-cookie/js-cookie-release/issues/3)</strike>
- [x] <strike>Build routine to commit (https://github.com/js-cookie/js-cookie-release/issues/4)
- [x] <strike>Build routine to push `master` changes to the server (https://github.com/js-cookie/js-cookie-release/issues/5)</strike>
- [x] <strike>Build routine to replace file content based on a provided algorithm (https://github.com/js-cookie/js-cookie-release/issues/6)</strike>
- [ ] <strike>Build routine to create a version tag and change the `latest` tag pointer (https://github.com/js-cookie/js-cookie-release/issues/7)</strike>
- [ ] <strike>Build a routine to publish to npm (https://github.com/js-cookie/js-cookie-release/issues/8)</strike>
- [ ] <strike>Add to the README the fundamentals behind the project (https://github.com/js-cookie/js-cookie-release/issues/9)</strike>
- [ ] <strike>Add to the README the API to be consumed by js-cookie to remove the manual release process (https://github.com/js-cookie/js-cookie-release/issues/10)</strike>

Moved to https://github.com/js-cookie/js-cookie-release/projects/2

**New Requirements for js-cookie**
- [ ] When publishing to npm, provide the minified version along with the source
- [ ] Document the cdnjs URL in the README that changes after each release
- [ ] Create a `js.cookie.debug.js` file before each release and document how to use it

X-Ref: https://github.com/js-cookie/js-cookie/pull/82 and https://github.com/js-cookie/js-cookie/issues/57.
